var swVersion='0.3';var cookieName='notification-version-_clarin';var notificationVersionCookie=$.cookie(cookieName);var isCookieSet=!notificationVersionCookie?false:true;var user=WAuth.getUserSync();var serviceWorker="notifications.js?v0.3";var now=new Date();function syntaxHighlight(json){if(typeof json!='string'){json=JSON.stringify(json,undefined,2);}
json=json.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return json.replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g,function(match){var cls='number';if(/^"/.test(match)){if(/:$/.test(match)){cls='key';}else{cls='string';}}else if(/true|false/.test(match)){cls='boolean';}else if(/null/.test(match)){cls='null';}
return '<span class="'+cls+'">'+match+'</span>';});}
function pintarJson(data){var tmpData=JSON.parse(data);var _datosJson=JSON.stringify(tmpData,null,'\t');var d=new Date();$("#notificaciones").css('visibility','visible');$("#notificaciones").html("<span class='notificacionTitulo'>Notificación Recibida - "+d.getDate()+"/"+(d.getMonth()+1)+"/"+d.getFullYear()+" "+d.getHours()+":"+d.getMinutes()+"</span><br/><pre>"+syntaxHighlight(_datosJson)+"</pre>");}
function detectIE(){var ua=window.navigator.userAgent;var msie=ua.indexOf('MSIE ');if(msie>0){return true;}
var trident=ua.indexOf('Trident/');if(trident>0){return true;}
var edge=ua.indexOf('Edge/');if(edge>0){return true;}
return false;}
function iOS(){var iDevices=['iPad Simulator','iPhone Simulator','iPod Simulator','iPad','iPhone','iPod'];if(!!navigator.platform){while(iDevices.length){if(navigator.platform===iDevices.pop()){return true;}}}
return false;}
function SWRegister(){if($.cookie('notification-_clarin')=="si"){if('serviceWorker'in navigator){navigator.serviceWorker.getRegistrations().then(function(arr){if(!arr.length){navigator.serviceWorker.register('/'+serviceWorker).then(function(reg){_clarin.sw.serviceWorker=reg;console.log('Service Worker Registered',reg);});}else{arr.forEach(function(el,i){if(el.active.scriptURL!="https\u003A\/\/www.clarin.com/notifications.js?v0.3"){el.unregister().then(function(boolean){$.cookie('notification-version-_clarin',null,{path:'/'});window.localStorage.removeItem('notification-version-_clarin');console.log('Service Worker UnRegistered');navigator.serviceWorker.register('/'+serviceWorker).then(function(reg){_clarin.sw.serviceWorker=reg;console.log('New Service Worker Registered',reg);});});}else{_clarin.sw.serviceWorker=el;}});}
$(document).trigger('service-worker-registered');});}}}
$(document).on('service-worker-registered',function(){try{if(['granted','default'].includes(Notification.permission)){_clarin.sw.firebase.appendScript(function(err){if(typeof err!="undefined"){firebase.initializeApp(_clarin.sw.firebase.getConfig());window.messaging=firebase.messaging();window.messaging.useServiceWorker(_clarin.sw.serviceWorker);}
console.log("entre a initialize");messaging.getToken().then(function(token){if(token){console.log("token: "+token);if(localStorage.getItem('notification-token')!=token){localStorage.setItem('notification-token',token);$.ajax({method:'post',url:'/commons/sw/notifications/activate',data:'token='+token+'&product=clarin',success:function(data){console.log("SW registrado");console.log("datos: "+data);window.localStorage.setItem('notification-version-_clarin','0.3');$.cookie('notification-version-{ service_worker_config.swSiteKey }}','0.3',{expires:new Date(now.getFullYear()+1,now.getMonth(),now.getDate())});}});}
if(localStorage.getItem('notification-_clarin-user')=='no'){if(user){$.ajax({method:'post',url:'/notification/activate',data:'uid='+user.uid+'&sid='+user.sessionId+'&token='+token+'&product=clarin',success:function(){window.localStorage.setItem('notification-_clarin-user','si');$.cookie('notification-_clarin-user','si',{expires:new Date(now.getFullYear()+1,now.getMonth(),now.getDate())});}});}}}}).catch(function(e){console.log(e);});});}}catch(e){console.error(e);}});function setData(key,value){$.cookie(key,value,{expires:new Date(now.getFullYear()+1,now.getMonth(),now.getDate()),path:'/'});window.localStorage.setItem(key,value);}
var swConfirmacion=function(msg){var msg=typeof msg=='undefined'?"Recibí nuestras noticias de último momento":msg;if(Notification.permission=='denied'){$(document).trigger('sw-confirmation-notification-rejected');return false;}
var dialog='<div class="notification-popup modal-dialog sw">';dialog+='<h2><img src="https\u003A\/\/images.clarin.com\/collections\/static\/logo_clarin.svg"></h2>';dialog+='<div class="content"><p>'+msg+'</p></div>';dialog+='<div class="actions">';dialog+='<div id="buttons"><button type="button" class="btns btnNo" >NO, GRACIAS</button> ';dialog+='<button type="button" class="btns btnSi ">RECIBIR</button></div>';dialog+='</div>';dialog+='</div>';$.magnificPopup.open({modal:true,fixedContentPos:false,showCloseBtn:true,closeOnBgClick:true,items:{src:dialog,type:'inline'},callbacks:{open:function(){var $content=$(this.content);$content.on('click','.btnSi',function(){sendGAPageview({'event':"trackEvent",'eventCategory':"Modal Alerta web",'eventAction':"Aceptar",'eventLabel':"Home"});if(Notification.permission=='default'){Notification.requestPermission().then(function(response){if(response!="granted"){sendGAPageview({'event':"trackEvent",'eventCategory':"Modal Alerta web",'eventAction':"Rechazar",'eventLabel':"Home"});setData('notification-_clarin','no');location.reload();return false;}else{setData('notification-_clarin','si');if(user){setData('notification-_clarin-user','si');}else{setData('notification-_clarin-user','no');}
SWRegister();$(document).trigger('sw-confirmation-notification-accepted');}});}else if(Notification.permission=='granted'){setData('notification-_clarin','si');if(user){setData('notification-_clarin-user','si');}else{setData('notification-_clarin-user','no');}
SWRegister();$(document).trigger('sw-confirmation-notification-accepted');}
if(Notification.permission=='denied')
return false
$.magnificPopup.close();$(document).off('keydown',keydownHandler);});$content.on('click','.btnNo',function(){sendGAPageview({'event':"trackEvent",'eventCategory':"Modal Alerta web",'eventAction':"Rechazar",'eventLabel':"Home"});setData('notification-_clarin','no');$.magnificPopup.close();$(document).off('keydown',keydownHandler);});$(document).on('click','.mfp-container',function(){sendGAPageview({'event':"trackEvent",'eventCategory':"Modal Alerta web",'eventAction':"Rechazar",'eventLabel':"Home"});setData('notification-_clarin','no');$.magnificPopup.close();$(document).off('keydown',keydownHandler);});var keydownHandler=function(e){if(e.keyCode==13){$content.find('.btnSi').click();return false;}else if(e.keyCode==27){$content.find('.btnNo').click();return false;}};$(document).on('keydown',keydownHandler);}}});};var swReConfirmacion=function(){swConfirmacion("Tenes las notificaciones rechazadas en tu navegador, deseas recibir nuestras notificaciones en tu navegador");};$(document).ready(function(){if(!window._clarin)
_clarin={};_clarin.store={_db:'',_os:'',openStream:false,_schema:{stores:{}},getIDDB:function(){var indexedDB=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB||window.shimIndexedDB||false;if(!indexedDB){throw "unsupported";return;}
return indexedDB;},deleteDb:function(dbName){return this.getIDDB().deleteDatabase(dbName);},createSchema:function(){var db=this.openStream.result;for(var i=0,len=Object.keys(this._schema.stores).length;i<len;i++){var storeName=Object.keys(this._schema.stores)[i];var primary=this._schema.stores[storeName].primary;var store=db.createObjectStore(storeName,{keyPath:primary});for(var j=0,lenIndexes=Object.keys(this._schema.stores[storeName].indexes).length;j<lenIndexes;j++){var index=this._schema.stores[storeName].indexes[j];store.createIndex(index.indexName,index.indexField);}}},getDb:function(db,version){db=db||this._db;version=version||1;var indexedDB=this.getIDDB();if(this.openStream){return this.openStream;}
this.openStream=indexedDB.open(db,version);return this.openStream;}};var ios=iOS();if(ios==true||detectIE()==true||navigator.appVersion.indexOf("Edge")!=-1){return;}
isPrivate(function(){$(document).trigger('sw-not-supported');},function(){if(Notification.permission!='denied'){if(typeof $.cookie('notification-_clarin')=="undefined"||!localStorage.getItem('notification-_clarin')){if(localStorage.getItem('notification-_clarin')){$.cookie('notification-_clarin',localStorage.getItem('notification-_clarin'),{expires:new Date(now.getFullYear()+1,now.getMonth(),now.getDate())});}
else if(typeof $.cookie('notification-_clarin')!="undefined"){window.localStorage.setItem('notification-_clarin',$.cookie('notification-_clarin'));}}
if($.cookie('notification-_clarin')=="si"){SWRegister();$(document).trigger('sw-registration-ready');}else if($.cookie('notification-_clarin')!="no"){if(window.location.href=="https://www.clarin.com/"){swConfirmacion();}else{$(document).trigger('sw-confirmation-pending');}}else{$(document).trigger('sw-confirmation-denied');}}});});